package manager;

import javax.swing.*;
import java.awt.*;

public class DashBoardGui extends JFrame {
    private JLabel status;
    private JPanel panel;
    private JLabel sugarAmount;
    private JLabel glassesAmount;

    public DashBoardGui() {
        setSize(550, 500);
        setTitle("Manager DashBoard");
        getContentPane().add(this.panel);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    public void setStatusLabel(final String status) {
        this.status.setText(status);
    }

    public void setSugarAmountLabel(final String sugarAmount) {
        this.sugarAmount.setText(sugarAmount);
    }

    public void setGlassesAmountLabel(final String glassesAmount) {
        this.glassesAmount.setText(glassesAmount);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        status = new JLabel();
        status.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(status, gbc);
        sugarAmount = new JLabel();
        sugarAmount.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(sugarAmount, gbc);
        glassesAmount = new JLabel();
        glassesAmount.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(glassesAmount, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
